<?php
// Auto-generated by Pure PHP Installer on 2026-04-19 19:35:08
return [
    'host'     => 'localhost',
    'port'     => 3306,
    'database' => 'purephp',
    'username' => 'root',
    'password' => '',
    'charset'  => 'utf8mb4',
];