<?php
// Auto-generated by Pure PHP Installer — 
// <?= date('Y-m-d H:i:s') 

return [
    'host'     => 'localhost',
    'port'     => 3306,
    'database' => 'purephp',
    'username' => 'root',
    'password' => '',
    'charset'  => 'utf8mb4',
];